// Live commentary generated by Claude (Haiku, direct browser, BYO key in localStorage).
// One short line that reacts to a specific score — roasting EITHER player. Each line comes in two
// forms: `tagged` (ElevenLabs v3 audio tags kept) and `plain` (tags stripped, for Web Speech and
// the on-screen caption). The orchestration (per-score trigger, voice, debounce) lives in
// commentary.js; this module is just the text generator + helpers.
//
// The Anthropic key is stored ONLY in localStorage and sent ONLY to api.anthropic.com.

const KEY_STORAGE = 'yz_anthropic_key';
const MODEL = 'claude-haiku-4-5-20251001';   // fast + cheap ($1/$5 per 1M tokens)
const ENDPOINT = 'https://api.anthropic.com/v1/messages';

const SYSTEM = [
  'You are the live commentator for a fast, friendly two-player Yahtzee game between Dan and Amber, but you are UNHINGED: an insult-comic-meets-cable-news-pundit who treats every dice roll like a breaking national scandal. Be genuinely, weirdly funny.',
  'React to the score you are told about. Roast EITHER player hard as the moment demands, and take a side with total confidence. Go for the biggest laugh: surprise, absurd specificity, a savage turn of phrase. Land a real joke, never a generic insult.',
  'Each line gets a random DELIVERY PERSONA and a SENTENCE SHAPE. Commit completely and lean in hard; they are your engine of variety, so never settle into one recognizable house voice.',
  'Be bold and weird: invent confident fake statistics, spin conspiracy theories about their dice, deliver mock-political attack-ad bombast and pundit ranting, take wild tangents, escalate into absurdity. "Political" is a comedic STYLE only (attack-ad / pundit theater) about the GAME and these two players, never real-world partisanship and never real people or groups.',
  'Build the joke out of the SPECIFIC situation (the exact number, the box they torched, the gap, a cold streak) then twist it: an unexpected comparison, a vivid image, misdirection, a little wordplay. Do not flatly recite the stats.',
  'Craft matters: keep it tight and cut filler. Output ONE short spoken line — never more than ~20 words, and usually much shorter. Put the funniest word last. A three-word verdict is great; just never ramble.',
  'Do NOT reuse a joke, comparison, metaphor, or punchline structure from the recent lines you are shown; find a genuinely different angle each time. You MAY call back to an earlier bit only if the callback itself is the joke.',
  'When given RIVALRY HISTORY, weaponize it for extra sting or a callback (a losing streak, a personal best they are nowhere near, how last game went) but only when it sharpens the joke; never just recite it.',
  'When told it is a players LAST TURN, treat it as a final-box moment: crank the tension or mock the pressure mercilessly.',
  'You may use at most one or two ElevenLabs v3 performance tags in square brackets, e.g. [dryly], [gleeful], [low], [laughs], [yelling], to color delivery.',
  'SAVAGERY LADDER (you will be told the level, 1 to 5): L1 cheeky and light. L2 sharper sarcasm. L3 gallows humor. L4 properly savage. L5 peak comedic cruelty, but funny first, cruel second.',
  'HARD RULES at EVERY level: no slurs; nothing about protected characteristics (race, gender, religion, orientation, disability); no jabs at appearance, weight, or real insecurities; no sexual content. Roast their Yahtzee play and competence only, affection underneath.',
  'Output ONE spoken line (occasionally two short ones for a big moment). No emoji, no stage directions in parentheses, no quotation marks around the line.',
].join(' ');

// Rotating comedic angle + sentence shape — the biggest lever for variety. One of each is picked
// per call and put in the user message; the angle never repeats back-to-back.
export const ANGLES = [
  'a deadpan statistician', 'a breathless sports play-by-play announcer', 'a mock-Shakespearean bard',
  'a grim true-crime narrator', 'a quietly disappointed parent', 'a hushed nature-documentary narrator',
  'an unhinged hype-beast', 'a world-weary noir detective', 'a manic infomercial host',
  'a passive-aggressive coworker', 'a paranoid conspiracy theorist', 'a theatrical fortune teller',
  'a snobbish wine critic', 'an exhausted air-traffic controller',
  'a mudslinging attack-ad narrator', 'a doomsday street preacher', 'a supermarket-tabloid headline writer',
  'a washed-up cable-news pundit', 'an insult comic working a hostile room',
];
export const SHAPES = [
  'a one-word verdict', 'a fabricated statistic', 'a backhanded compliment', 'a mock threat',
  'a rhetorical question', 'a fake news headline', 'a single brutal metaphor', 'an overheard aside',
];

const RECENT_MAX = 6;
let enabled = false;
const seen = new Set();
const recent = [];        // last few generated lines (self-memory, threaded into the prompt)
let lastAngle = null;

export function pickDelivery() {
  let angle = ANGLES[Math.floor(Math.random() * ANGLES.length)];
  if (angle === lastAngle && ANGLES.length > 1) {
    const others = ANGLES.filter(a => a !== lastAngle);
    angle = others[Math.floor(Math.random() * others.length)];
  }
  lastAngle = angle;
  return { angle, shape: SHAPES[Math.floor(Math.random() * SHAPES.length)] };
}

function getKey() { try { return localStorage.getItem(KEY_STORAGE) || ''; } catch { return ''; } }
function putKey(k) { try { if (k) localStorage.setItem(KEY_STORAGE, k); else localStorage.removeItem(KEY_STORAGE); } catch { /* ignore */ } }

// ---- line parsing: keep v3 [tags] in `tagged`, strip them for `plain` ----
function cleanCommon(s) {
  let t = (s || '').replace(/\s+/g, ' ').trim();
  t = t.replace(/\([^)]*\)/g, '').replace(/\*[^*]*\*/g, '');
  t = t.replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}\u{FE0F}]/gu, '');
  t = t.replace(/^["'“”\s]+|["'“”\s]+$/g, '').replace(/\s+/g, ' ').trim();
  return t.length > 260 ? t.slice(0, 260) : t;
}
export function stripTags(s) { return (s || '').replace(/\[[^\]]*\]/g, ' ').replace(/\s+/g, ' ').trim(); }
export function parseLine(raw) { const tagged = cleanCommon(raw); return { tagged, plain: stripTags(tagged) }; }

// ---- length cap: ~10s of speech is roughly ~25 words, so keep every line under ~20-22 words ----
const MAX_WORDS = 22;        // over this -> re-roll / trim
const MAX_CHARS = 140;
const TRIM_WORDS = 20;       // cap when trimming to the first one or two sentences
export function wordCount(s) { return ((s || '').trim().match(/\S+/g) || []).length; }
export function isTooLong(plain) { return wordCount(plain) > MAX_WORDS || (plain || '').length > MAX_CHARS; }
// Keep the first `max` spoken words (bracketed [tags] don't count toward the limit but are preserved).
function hardCapWords(text, max) {
  const kept = []; let words = 0;
  for (const tk of (text.match(/\S+/g) || [])) {
    kept.push(tk);
    if (!/^\[[^\]]*\]$/.test(tk)) { words++; if (words >= max) break; }
  }
  return kept.join(' ');
}
// Trim a tagged line to its first one or two sentences within the cap (keeps tags; re-derives plain).
// A single over-long sentence is hard-capped by word count so the spoken line still lands under ~10s.
export function trimLine({ tagged, plain }) {
  const parts = (tagged || '').match(/[^.!?]+[.!?]+|\S[^.!?]*$/g) || [tagged || ''];
  let out = '';
  for (const p of parts) {
    const cand = out + p;
    if (out && (wordCount(stripTags(cand)) > TRIM_WORDS || cand.length > MAX_CHARS)) break;
    out = cand;
    if (wordCount(stripTags(out)) >= TRIM_WORDS) break;
  }
  out = (out.trim() || (tagged || '').trim());
  if (wordCount(stripTags(out)) > TRIM_WORDS) out = hardCapWords(out, TRIM_WORDS);
  return { tagged: out.trim(), plain: stripTags(out).trim() || plain };
}

// ---- escalation: progress (0..1) -> savagery level (1..5), clamped by a cap ----
export function savageryLevel(progress, cap = 5) {
  const p = Math.max(0, Math.min(1, Number(progress) || 0));
  const lvl = p < 0.20 ? 1 : p < 0.40 ? 2 : p < 0.60 ? 3 : p < 0.85 ? 4 : 5;
  const c = Math.max(1, Math.min(5, Math.round(Number(cap) || 5)));
  return Math.min(lvl, c);
}

function rivalryLine(r) {
  const names = Object.keys(r.wins || {});
  const parts = [];
  if (names.length === 2) parts.push(`Career: ${names[0]} ${r.wins[names[0]]}-${r.wins[names[1]]} ${names[1]}${r.ties ? ` (${r.ties} tie${r.ties > 1 ? 's' : ''})` : ''} over ${r.totalGames} games.`);
  if (r.streak && r.streak.name && r.streak.length >= 2) parts.push(`${r.streak.name} has won the last ${r.streak.length}.`);
  if (r.lastWinner) parts.push(`Last game went to ${r.lastWinner}.`);
  if (r.avg && names.length === 2) parts.push(`Career averages: ${names[0]} ${r.avg[names[0]]}, ${names[1]} ${r.avg[names[1]]}.`);
  if (r.bestGame && r.bestGame.name) parts.push(`Record game: ${r.bestGame.name} ${r.bestGame.score}.`);
  return 'RIVALRY HISTORY (reference occasionally for spice, do NOT force it every line): ' + parts.join(' ');
}

export function buildUserMessage(c, { angle, shape, recent: recentLines } = {}) {
  const lvl = c.level || 1;
  const L = [`Savagery level ${lvl} of 5.`, c.profanity ? 'Mild profanity allowed for comedic punch.' : 'Keep it clean — no profanity.'];
  if (angle || shape) L.push(`Deliver THIS line as ${angle || 'yourself'}${shape ? `, in the form of ${shape}` : ''}.`);
  const recentTail = () => { if (recentLines && recentLines.length) L.push(`Recent lines you've already said (do NOT reuse their structure or jokes; you MAY call back to one if it lands): ${recentLines.map(r => `"${r}"`).join(' / ')}.`); };

  if (c.gameOver) {
    if (c.tie) L.push(`GAME OVER — a TIE at ${c.winScore}. Roast both Dan and Amber.`);
    else L.push(`GAME OVER. ${c.winner} beat ${c.loser} ${c.winScore} to ${c.loseScore}.`);
    L.push('Give the closing line: hype the winner and roast the loser (or roast both on a tie).');
    if (c.rivalry) L.push(rivalryLine(c.rivalry));
    recentTail();
    return L.join(' ');
  }
  L.push(`${c.scorer} just scored ${c.category}${c.value != null ? ` for ${c.value}` : ''}.`);
  if (c.justYahtzee) L.push('That was a YAHTZEE (fifty).');
  if (c.justBonus) L.push('That was a BONUS Yahtzee, plus one hundred.');
  if (c.justScratched) L.push(`${c.scorer} SCRATCHED it for a zero.`);
  if (c.wasChance) L.push('It went in Chance, the freebie box.');
  L.push(`Totals now: ${c.scorer} ${c.scorerTotal}, ${c.opponent} ${c.opponentTotal}.`);
  L.push(c.margin === 0 ? 'The game is tied.' : `${c.leader} leads by ${c.margin}.`);
  if (c.comeback) L.push(`COMEBACK: ${c.comeback}.`);
  L.push(`Upper bonus: ${c.scorer} ${c.scorerBonusSecured ? 'has the +35' : `needs ${c.scorerBonusDist} more`}; ${c.opponent} ${c.opponentBonusSecured ? 'has the +35' : `needs ${c.opponentBonusDist} more`}.`);
  L.push(`Boxes left: ${c.scorer} ${c.scorerBoxesLeft}, ${c.opponent} ${c.opponentBoxesLeft}.`);
  if (c.needToWin) L.push(c.needToWin);
  if (c.trends && c.trends.length) L.push('Trends: ' + c.trends.join('; ') + '.');
  if (c.jabs && c.jabs.length) L.push('Jab fodder: ' + c.jabs.join('; ') + '.');
  if (c.scorerLastTurn) L.push(`This is ${c.scorer}s LAST TURN, final box.`);
  else if (c.opponentLastTurn) L.push(`${c.opponent} is down to their LAST box.`);
  if (c.rivalry) L.push(rivalryLine(c.rivalry));
  recentTail();
  L.push('Now give one fresh line — commit to the persona and shape above, and surprise me.');
  return L.join(' ');
}

async function callAPI(key, userMessage, timeoutMs = 8000, signal) {
  const ctrl = new AbortController();
  const onAbort = () => ctrl.abort();
  if (signal) { if (signal.aborted) ctrl.abort(); else signal.addEventListener('abort', onAbort, { once: true }); }
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  let res;
  try {
    res = await fetch(ENDPOINT, {
      method: 'POST',
      signal: ctrl.signal,
      headers: {
        'content-type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      // temperature is capped at 1.0 by the API (1.1 -> 400); keep it at the max for variety.
      body: JSON.stringify({ model: MODEL, max_tokens: 60, temperature: 1, system: SYSTEM, messages: [{ role: 'user', content: userMessage }] }),
    });
  } finally { clearTimeout(timer); if (signal) signal.removeEventListener('abort', onAbort); }
  if (!res.ok) {
    let detail = ''; try { detail = (await res.json())?.error?.message || ''; } catch { /* ignore */ }
    throw new Error(`HTTP ${res.status}${detail ? ' — ' + detail : ''}`);
  }
  const data = await res.json();
  const text = (data.content || []).filter(b => b.type === 'text').map(b => b.text).join(' ');
  if (!text.trim()) throw new Error('empty response');
  return text;
}

export const AIPep = {
  setEnabled(on) { enabled = on; },
  isEnabled() { return enabled; },
  hasKey() { return !!getKey(); },
  ready() { return enabled && !!getKey(); },
  setKey(k) { putKey((k || '').trim()); },
  maskedKey() { const k = getKey(); return k ? k.slice(0, 10) + '…' + k.slice(-4) : ''; },

  // Generate one line for a specific context. Returns { tagged, plain } or null (no key, dup,
  // aborted, or error). Supports an AbortSignal so an in-flight line can be cancelled.
  async generateLine(ctx, { signal } = {}) {
    if (!this.ready()) return null;
    const accept = (line) => { seen.add(line.plain); recent.push(line.plain); if (recent.length > RECENT_MAX) recent.shift(); return line; };
    let overLong = null;   // an over-long candidate held from attempt 0; trimmed as a last resort
    for (let attempt = 0; attempt < 2; attempt++) {     // one retry, then accept rather than go silent
      try {
        const { angle, shape } = pickDelivery();
        const userMessage = buildUserMessage(ctx, { angle, shape, recent: recent.slice() });
        const { tagged, plain } = parseLine(await callAPI(getKey(), userMessage, 8000, signal));
        if (!plain) continue;
        if (seen.has(plain) && attempt === 0) continue;  // dup on first try -> regenerate
        if (isTooLong(plain) && attempt === 0) { overLong = { tagged, plain }; continue; }  // too long -> re-roll once
        return accept(isTooLong(plain) ? trimLine({ tagged, plain }) : { tagged, plain });
      } catch { if (signal && signal.aborted) return null; }  // superseded -> stop; else retry/exit
    }
    if (overLong) return accept(trimLine(overLong));   // re-roll exhausted -> trim rather than go silent
    return null;
  },

  // One-off probe for the settings "Test" button.
  async test(key) {
    const k = (key || getKey() || '').trim();
    if (!k) return { ok: false, error: 'No key' };
    const sample = {
      level: 3, scorer: 'Amber', opponent: 'Dan', category: 'Yahtzee', value: 50, justYahtzee: true,
      scorerTotal: 158, opponentTotal: 121, leader: 'Amber', margin: 37,
      scorerBonusSecured: true, scorerBonusDist: 0, opponentBonusSecured: false, opponentBonusDist: 9,
      scorerBoxesLeft: 4, opponentBoxesLeft: 5, jabs: ['Dan scratched Aces & Twos'],
    };
    try {
      const { angle, shape } = pickDelivery();
      return { ok: true, text: parseLine(await callAPI(k, buildUserMessage(sample, { angle, shape }), 12000)).plain };
    } catch (e) { return { ok: false, error: String(e?.message || e) }; }
  },
};
