// Live commentary generated by Claude (Haiku, direct browser, BYO key in localStorage).
// One short line that reacts to a specific score — roasting EITHER player. Each line comes in two
// forms: `tagged` (ElevenLabs v3 audio tags kept) and `plain` (tags stripped, for Web Speech and
// the on-screen caption). The orchestration (per-score trigger, voice, debounce) lives in
// commentary.js; this module is just the text generator + helpers.
//
// The Anthropic key is stored ONLY in localStorage and sent ONLY to api.anthropic.com.

const KEY_STORAGE = 'yz_anthropic_key';
const MODEL = 'claude-haiku-4-5-20251001';   // fast + cheap ($1/$5 per 1M tokens)
const ENDPOINT = 'https://api.anthropic.com/v1/messages';

const SYSTEM = [
  'You are the live, ringside color commentator for a fast, friendly two-player Yahtzee game between Dan and Amber.',
  'React to the score you are told about with ONE short spoken sentence (at most two for a huge moment).',
  'You roast BOTH players — whoever the moment calls for, and you may take a side. Mostly comedic roast, with the occasional sincere or witty-inspiring beat.',
  'Be specific: use the real names, the running totals, what someone still needs, a weak upper number, an untouched Chance, a brutal scratch, or a comeback — pick what FITS this moment, not all at once.',
  'You may include at most one or two ElevenLabs v3 performance tags in square brackets, e.g. [dryly], [gleeful], [low], [laughs], to color delivery.',
  'SAVAGERY LADDER (you will be told the level, 1 to 5): L1 cheeky and light. L2 sharper sarcasm. L3 gallows humor, mock-villain swagger. L4 properly savage. L5 peak comedic cruelty, full theatrical villainy.',
  'HARD RULES at EVERY level: no slurs; nothing about protected characteristics (race, gender, religion, orientation, disability); no jabs at appearance, weight, or real insecurities; no sexual content. Roast their Yahtzee play and competence only — affection underneath.',
  'No emoji. No stage directions in parentheses. No quotation marks around the line.',
].join(' ');

let enabled = false;
const seen = new Set();

function getKey() { try { return localStorage.getItem(KEY_STORAGE) || ''; } catch { return ''; } }
function putKey(k) { try { if (k) localStorage.setItem(KEY_STORAGE, k); else localStorage.removeItem(KEY_STORAGE); } catch { /* ignore */ } }

// ---- line parsing: keep v3 [tags] in `tagged`, strip them for `plain` ----
function cleanCommon(s) {
  let t = (s || '').replace(/\s+/g, ' ').trim();
  t = t.replace(/\([^)]*\)/g, '').replace(/\*[^*]*\*/g, '');
  t = t.replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}\u{FE0F}]/gu, '');
  t = t.replace(/^["'“”\s]+|["'“”\s]+$/g, '').replace(/\s+/g, ' ').trim();
  return t.length > 260 ? t.slice(0, 260) : t;
}
export function stripTags(s) { return (s || '').replace(/\[[^\]]*\]/g, ' ').replace(/\s+/g, ' ').trim(); }
export function parseLine(raw) { const tagged = cleanCommon(raw); return { tagged, plain: stripTags(tagged) }; }

// ---- escalation: progress (0..1) -> savagery level (1..5), clamped by a cap ----
export function savageryLevel(progress, cap = 5) {
  const p = Math.max(0, Math.min(1, Number(progress) || 0));
  const lvl = p < 0.20 ? 1 : p < 0.40 ? 2 : p < 0.60 ? 3 : p < 0.85 ? 4 : 5;
  const c = Math.max(1, Math.min(5, Math.round(Number(cap) || 5)));
  return Math.min(lvl, c);
}

export function buildUserMessage(c) {
  const lvl = c.level || 1;
  const L = [`Savagery level ${lvl} of 5.`, c.profanity ? 'Mild profanity allowed for comedic punch.' : 'Keep it clean — no profanity.'];
  if (c.gameOver) {
    if (c.tie) L.push(`GAME OVER — a TIE at ${c.winScore}. Roast both Dan and Amber.`);
    else L.push(`GAME OVER. ${c.winner} beat ${c.loser} ${c.winScore} to ${c.loseScore}.`);
    L.push('Give the closing line: hype the winner and roast the loser (or roast both on a tie).');
    return L.join(' ');
  }
  L.push(`${c.scorer} just scored ${c.category}${c.value != null ? ` for ${c.value}` : ''}.`);
  if (c.justYahtzee) L.push('That was a YAHTZEE (fifty).');
  if (c.justBonus) L.push('That was a BONUS Yahtzee, plus one hundred.');
  if (c.justScratched) L.push(`${c.scorer} SCRATCHED it for a zero.`);
  if (c.wasChance) L.push('It went in Chance, the freebie box.');
  L.push(`Totals now: ${c.scorer} ${c.scorerTotal}, ${c.opponent} ${c.opponentTotal}.`);
  L.push(c.margin === 0 ? 'The game is tied.' : `${c.leader} leads by ${c.margin}.`);
  if (c.comeback) L.push(`COMEBACK: ${c.comeback}.`);
  L.push(`Upper bonus: ${c.scorer} ${c.scorerBonusSecured ? 'has the +35' : `needs ${c.scorerBonusDist} more`}; ${c.opponent} ${c.opponentBonusSecured ? 'has the +35' : `needs ${c.opponentBonusDist} more`}.`);
  L.push(`Boxes left: ${c.scorer} ${c.scorerBoxesLeft}, ${c.opponent} ${c.opponentBoxesLeft}.`);
  if (c.needToWin) L.push(c.needToWin);
  if (c.jabs && c.jabs.length) L.push('Jab fodder: ' + c.jabs.join('; ') + '.');
  L.push('Now give one fresh line that fits this exact moment.');
  return L.join(' ');
}

async function callAPI(key, ctx, timeoutMs = 8000, signal) {
  const ctrl = new AbortController();
  const onAbort = () => ctrl.abort();
  if (signal) { if (signal.aborted) ctrl.abort(); else signal.addEventListener('abort', onAbort, { once: true }); }
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  let res;
  try {
    res = await fetch(ENDPOINT, {
      method: 'POST',
      signal: ctrl.signal,
      headers: {
        'content-type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify({ model: MODEL, max_tokens: 110, temperature: 1, system: SYSTEM, messages: [{ role: 'user', content: buildUserMessage(ctx) }] }),
    });
  } finally { clearTimeout(timer); if (signal) signal.removeEventListener('abort', onAbort); }
  if (!res.ok) {
    let detail = ''; try { detail = (await res.json())?.error?.message || ''; } catch { /* ignore */ }
    throw new Error(`HTTP ${res.status}${detail ? ' — ' + detail : ''}`);
  }
  const data = await res.json();
  const text = (data.content || []).filter(b => b.type === 'text').map(b => b.text).join(' ');
  if (!text.trim()) throw new Error('empty response');
  return text;
}

export const AIPep = {
  setEnabled(on) { enabled = on; },
  isEnabled() { return enabled; },
  hasKey() { return !!getKey(); },
  ready() { return enabled && !!getKey(); },
  setKey(k) { putKey((k || '').trim()); },
  maskedKey() { const k = getKey(); return k ? k.slice(0, 10) + '…' + k.slice(-4) : ''; },

  // Generate one line for a specific context. Returns { tagged, plain } or null (no key, dup,
  // aborted, or error). Supports an AbortSignal so an in-flight line can be cancelled.
  async generateLine(ctx, { signal } = {}) {
    if (!this.ready()) return null;
    try {
      const { tagged, plain } = parseLine(await callAPI(getKey(), ctx, 8000, signal));
      if (!plain || seen.has(plain)) return null;   // keep lines unique within the session
      seen.add(plain);
      return { tagged, plain };
    } catch { return null; }
  },

  // One-off probe for the settings "Test" button.
  async test(key) {
    const k = (key || getKey() || '').trim();
    if (!k) return { ok: false, error: 'No key' };
    const sample = {
      level: 3, scorer: 'Amber', opponent: 'Dan', category: 'Yahtzee', value: 50, justYahtzee: true,
      scorerTotal: 158, opponentTotal: 121, leader: 'Amber', margin: 37,
      scorerBonusSecured: true, scorerBonusDist: 0, opponentBonusSecured: false, opponentBonusDist: 9,
      scorerBoxesLeft: 4, opponentBoxesLeft: 5, jabs: ['Dan scratched Aces & Twos'],
    };
    try { return { ok: true, text: parseLine(await callAPI(k, sample, 12000)).plain }; }
    catch (e) { return { ok: false, error: String(e?.message || e) }; }
  },
};
