// Live commentary generated by Claude (Haiku, direct browser, BYO key in localStorage).
// One short line that reacts to a specific score — roasting EITHER player. Each line comes in two
// forms: `tagged` (ElevenLabs v3 audio tags kept) and `plain` (tags stripped, for Web Speech and
// the on-screen caption). The orchestration (per-score trigger, voice, debounce) lives in
// commentary.js; this module is just the text generator + helpers.
//
// The Anthropic key is stored ONLY in localStorage and sent ONLY to api.anthropic.com.

const KEY_STORAGE = 'yz_anthropic_key';
const MODEL = 'claude-haiku-4-5-20251001';   // fast + cheap ($1/$5 per 1M tokens)
const ENDPOINT = 'https://api.anthropic.com/v1/messages';

const SYSTEM = [
  'You are the live, ringside color commentator for a fast, friendly two-player Yahtzee game between Dan and Amber.',
  'React to the score you are told about. You roast BOTH players — whoever the moment calls for, and you may take a side. Mostly comedic roast, with the occasional sincere or witty beat.',
  'Each line you will be assigned a random DELIVERY PERSONA and a SENTENCE SHAPE — commit to them fully and lean in hard; they are your main source of variety, so do NOT fall back into a recognizable house voice.',
  'Use the facts when they are funny — names, totals, what someone needs, a weak number, a cold streak — but you may also just react to the vibe or fixate on one absurd detail. Do not recite stats dutifully.',
  'Vary the length a lot: sometimes three words, sometimes a full sentence. Avoid your own clichés and the structures of the recent lines you are shown.',
  'You may include at most one or two ElevenLabs v3 performance tags in square brackets, e.g. [dryly], [gleeful], [low], [laughs], to color delivery.',
  'SAVAGERY LADDER (you will be told the level, 1 to 5): L1 cheeky and light. L2 sharper sarcasm. L3 gallows humor. L4 properly savage. L5 peak comedic cruelty.',
  'HARD RULES at EVERY level: no slurs; nothing about protected characteristics (race, gender, religion, orientation, disability); no jabs at appearance, weight, or real insecurities; no sexual content. Roast their Yahtzee play and competence only — affection underneath.',
  'Output ONE spoken line (occasionally two short ones for a big moment). No emoji, no stage directions in parentheses, no quotation marks around the line.',
].join(' ');

// Rotating comedic angle + sentence shape — the biggest lever for variety. One of each is picked
// per call and put in the user message; the angle never repeats back-to-back.
export const ANGLES = [
  'a deadpan statistician', 'a breathless sports play-by-play announcer', 'a mock-Shakespearean bard',
  'a grim true-crime narrator', 'a quietly disappointed parent', 'a hushed nature-documentary narrator',
  'an unhinged hype-beast', 'a world-weary noir detective', 'a manic infomercial host',
  'a passive-aggressive coworker', 'a paranoid conspiracy theorist', 'a theatrical fortune teller',
  'a snobbish wine critic', 'an exhausted air-traffic controller',
];
export const SHAPES = [
  'a one-word verdict', 'a fabricated statistic', 'a backhanded compliment', 'a mock threat',
  'a rhetorical question', 'a fake news headline', 'a single brutal metaphor', 'an overheard aside',
];

let enabled = false;
const seen = new Set();
const recent = [];        // last few generated lines (self-memory, threaded into the prompt)
let lastAngle = null;

export function pickDelivery() {
  let angle = ANGLES[Math.floor(Math.random() * ANGLES.length)];
  if (angle === lastAngle && ANGLES.length > 1) {
    const others = ANGLES.filter(a => a !== lastAngle);
    angle = others[Math.floor(Math.random() * others.length)];
  }
  lastAngle = angle;
  return { angle, shape: SHAPES[Math.floor(Math.random() * SHAPES.length)] };
}

function getKey() { try { return localStorage.getItem(KEY_STORAGE) || ''; } catch { return ''; } }
function putKey(k) { try { if (k) localStorage.setItem(KEY_STORAGE, k); else localStorage.removeItem(KEY_STORAGE); } catch { /* ignore */ } }

// ---- line parsing: keep v3 [tags] in `tagged`, strip them for `plain` ----
function cleanCommon(s) {
  let t = (s || '').replace(/\s+/g, ' ').trim();
  t = t.replace(/\([^)]*\)/g, '').replace(/\*[^*]*\*/g, '');
  t = t.replace(/[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}\u{FE0F}]/gu, '');
  t = t.replace(/^["'“”\s]+|["'“”\s]+$/g, '').replace(/\s+/g, ' ').trim();
  return t.length > 260 ? t.slice(0, 260) : t;
}
export function stripTags(s) { return (s || '').replace(/\[[^\]]*\]/g, ' ').replace(/\s+/g, ' ').trim(); }
export function parseLine(raw) { const tagged = cleanCommon(raw); return { tagged, plain: stripTags(tagged) }; }

// ---- escalation: progress (0..1) -> savagery level (1..5), clamped by a cap ----
export function savageryLevel(progress, cap = 5) {
  const p = Math.max(0, Math.min(1, Number(progress) || 0));
  const lvl = p < 0.20 ? 1 : p < 0.40 ? 2 : p < 0.60 ? 3 : p < 0.85 ? 4 : 5;
  const c = Math.max(1, Math.min(5, Math.round(Number(cap) || 5)));
  return Math.min(lvl, c);
}

export function buildUserMessage(c, { angle, shape, recent: recentLines } = {}) {
  const lvl = c.level || 1;
  const L = [`Savagery level ${lvl} of 5.`, c.profanity ? 'Mild profanity allowed for comedic punch.' : 'Keep it clean — no profanity.'];
  if (angle || shape) L.push(`Deliver THIS line as ${angle || 'yourself'}${shape ? `, in the form of ${shape}` : ''}.`);
  const recentTail = () => { if (recentLines && recentLines.length) L.push(`Recent lines you've already said (do NOT reuse their structure or jokes; you MAY call back to one if it lands): ${recentLines.map(r => `"${r}"`).join(' / ')}.`); };

  if (c.gameOver) {
    if (c.tie) L.push(`GAME OVER — a TIE at ${c.winScore}. Roast both Dan and Amber.`);
    else L.push(`GAME OVER. ${c.winner} beat ${c.loser} ${c.winScore} to ${c.loseScore}.`);
    L.push('Give the closing line: hype the winner and roast the loser (or roast both on a tie).');
    recentTail();
    return L.join(' ');
  }
  L.push(`${c.scorer} just scored ${c.category}${c.value != null ? ` for ${c.value}` : ''}.`);
  if (c.justYahtzee) L.push('That was a YAHTZEE (fifty).');
  if (c.justBonus) L.push('That was a BONUS Yahtzee, plus one hundred.');
  if (c.justScratched) L.push(`${c.scorer} SCRATCHED it for a zero.`);
  if (c.wasChance) L.push('It went in Chance, the freebie box.');
  L.push(`Totals now: ${c.scorer} ${c.scorerTotal}, ${c.opponent} ${c.opponentTotal}.`);
  L.push(c.margin === 0 ? 'The game is tied.' : `${c.leader} leads by ${c.margin}.`);
  if (c.comeback) L.push(`COMEBACK: ${c.comeback}.`);
  L.push(`Upper bonus: ${c.scorer} ${c.scorerBonusSecured ? 'has the +35' : `needs ${c.scorerBonusDist} more`}; ${c.opponent} ${c.opponentBonusSecured ? 'has the +35' : `needs ${c.opponentBonusDist} more`}.`);
  L.push(`Boxes left: ${c.scorer} ${c.scorerBoxesLeft}, ${c.opponent} ${c.opponentBoxesLeft}.`);
  if (c.needToWin) L.push(c.needToWin);
  if (c.trends && c.trends.length) L.push('Trends: ' + c.trends.join('; ') + '.');
  if (c.jabs && c.jabs.length) L.push('Jab fodder: ' + c.jabs.join('; ') + '.');
  recentTail();
  L.push('Now give one fresh line — commit to the persona and shape above, and surprise me.');
  return L.join(' ');
}

async function callAPI(key, userMessage, timeoutMs = 8000, signal) {
  const ctrl = new AbortController();
  const onAbort = () => ctrl.abort();
  if (signal) { if (signal.aborted) ctrl.abort(); else signal.addEventListener('abort', onAbort, { once: true }); }
  const timer = setTimeout(() => ctrl.abort(), timeoutMs);
  let res;
  try {
    res = await fetch(ENDPOINT, {
      method: 'POST',
      signal: ctrl.signal,
      headers: {
        'content-type': 'application/json',
        'x-api-key': key,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      // temperature is capped at 1.0 by the API (1.1 -> 400); keep it at the max for variety.
      body: JSON.stringify({ model: MODEL, max_tokens: 110, temperature: 1, system: SYSTEM, messages: [{ role: 'user', content: userMessage }] }),
    });
  } finally { clearTimeout(timer); if (signal) signal.removeEventListener('abort', onAbort); }
  if (!res.ok) {
    let detail = ''; try { detail = (await res.json())?.error?.message || ''; } catch { /* ignore */ }
    throw new Error(`HTTP ${res.status}${detail ? ' — ' + detail : ''}`);
  }
  const data = await res.json();
  const text = (data.content || []).filter(b => b.type === 'text').map(b => b.text).join(' ');
  if (!text.trim()) throw new Error('empty response');
  return text;
}

export const AIPep = {
  setEnabled(on) { enabled = on; },
  isEnabled() { return enabled; },
  hasKey() { return !!getKey(); },
  ready() { return enabled && !!getKey(); },
  setKey(k) { putKey((k || '').trim()); },
  maskedKey() { const k = getKey(); return k ? k.slice(0, 10) + '…' + k.slice(-4) : ''; },

  // Generate one line for a specific context. Returns { tagged, plain } or null (no key, dup,
  // aborted, or error). Supports an AbortSignal so an in-flight line can be cancelled.
  async generateLine(ctx, { signal } = {}) {
    if (!this.ready()) return null;
    try {
      const { angle, shape } = pickDelivery();
      const userMessage = buildUserMessage(ctx, { angle, shape, recent: recent.slice() });
      const { tagged, plain } = parseLine(await callAPI(getKey(), userMessage, 8000, signal));
      if (!plain || seen.has(plain)) return null;   // keep lines unique within the session
      seen.add(plain);
      recent.push(plain); if (recent.length > 4) recent.shift();   // self-memory for callbacks / anti-repetition
      return { tagged, plain };
    } catch { return null; }
  },

  // One-off probe for the settings "Test" button.
  async test(key) {
    const k = (key || getKey() || '').trim();
    if (!k) return { ok: false, error: 'No key' };
    const sample = {
      level: 3, scorer: 'Amber', opponent: 'Dan', category: 'Yahtzee', value: 50, justYahtzee: true,
      scorerTotal: 158, opponentTotal: 121, leader: 'Amber', margin: 37,
      scorerBonusSecured: true, scorerBonusDist: 0, opponentBonusSecured: false, opponentBonusDist: 9,
      scorerBoxesLeft: 4, opponentBoxesLeft: 5, jabs: ['Dan scratched Aces & Twos'],
    };
    try {
      const { angle, shape } = pickDelivery();
      return { ok: true, text: parseLine(await callAPI(k, buildUserMessage(sample, { angle, shape }), 12000)).plain };
    } catch (e) { return { ok: false, error: String(e?.message || e) }; }
  },
};
